### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Sasa-won-keuns-lab** [metagentools/VStrains#1]
Hello, 

I would like to ask if there's something I missed out because i have tried both install method, but I can't make the command work. I attach the pict of my terminal here. I hope you can give me some advice on how to fix this. Thank you very much for your help.

![VStrains_problems](https://github.com/metagentools/VStrains/assets/153418103/e4c7b6fa-6e45-447e-b1da-b942861f0f43)

**Comment by RunpengLuo** [comment]
Hello, after installing the required libraries, you have to clone the repo and run pip install as the [next step](https://github.com/metagentools/VStrains?tab=readme-ov-file#download--install-vstrains)

**Comment by RunpengLuo** [comment]
Mark as resolved
